"""CarouselItem table creation

Revision ID: 52e84975a3e2
Revises: a60afce29ba1
Create Date: 2025-10-09 21:58:40.850297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e84975a3e2'
down_revision = 'a60afce29ba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    with op.batch_alter_table('carousel_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_position', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('button_text', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('button_link', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('img', sa.String(length=50), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('carousel_item', schema=None) as batch_op:
        batch_op.drop_column('img')
        batch_op.drop_column('button_link')
        batch_op.drop_column('button_text')
        batch_op.drop_column('text_position')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###
