"""Changed admin to user

Revision ID: de297c6726a3
Revises: c8652aaa023e
Create Date: 2025-10-22 22:30:31.277960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de297c6726a3'
down_revision = 'c8652aaa023e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('admin', 'user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user', 'admin')
    # ### end Alembic commands ###
